/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Toshiba
 */
public class FormInicio extends javax.swing.JFrame {

    /**
     * Creates new form FormInicio
     */
    public FormInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncons = new javax.swing.JButton();
        btnclie = new javax.swing.JButton();
        btnvend = new javax.swing.JButton();
        btnvehi = new javax.swing.JButton();
        btnfact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btncons.setText("Concesionario");
        btncons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsActionPerformed(evt);
            }
        });

        btnclie.setText("Clientes");
        btnclie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclieActionPerformed(evt);
            }
        });

        btnvend.setText("Vendedores");
        btnvend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvendActionPerformed(evt);
            }
        });

        btnvehi.setText("Vehiculos");
        btnvehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvehiActionPerformed(evt);
            }
        });

        btnfact.setText("Factura");
        btnfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncons)
                    .addComponent(btnvehi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnclie)
                            .addComponent(btnvend))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnfact, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncons)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnfact, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnclie)
                        .addGap(18, 18, 18)
                        .addComponent(btnvend)))
                .addGap(18, 18, 18)
                .addComponent(btnvehi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsActionPerformed
        FormInicio i = new FormInicio();
        FormConcesionario c = new FormConcesionario();
        i.setVisible(false);
        c.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnconsActionPerformed

    private void btnclieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclieActionPerformed
        FormInicio i = new FormInicio();
        FormCliente c = new FormCliente();
        i.setVisible(false);
        c.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnclieActionPerformed

    private void btnvendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvendActionPerformed
        FormInicio i = new FormInicio();
        FormVendedor v = new FormVendedor();
        i.setVisible(false);
        v.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnvendActionPerformed

    private void btnvehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvehiActionPerformed
        FormInicio i = new FormInicio();
        FormVehiculo c = new FormVehiculo();
        i.setVisible(false);
        c.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnvehiActionPerformed

    private void btnfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfactActionPerformed
        FormInicio i = new FormInicio();
        FormFactura c = new FormFactura();
        i.setVisible(false);
        c.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnfactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclie;
    private javax.swing.JButton btncons;
    private javax.swing.JButton btnfact;
    private javax.swing.JButton btnvehi;
    private javax.swing.JButton btnvend;
    // End of variables declaration//GEN-END:variables
}
